import { useState, type FormEvent } from "react";
import { Alert, Box, Button, Link, Stack, TextField, Typography } from "@mui/material";
import { useNavigate } from "react-router-dom";
import { requestPasswordReset, resetPassword } from "../../services/authService";
import { getErrorMessage } from "../../utils/getErrorMessage";

const ForgotPassword = () => {
  const navigate = useNavigate(); const [email, setEmail] = useState(""); const [otp, setOtp] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [step, setStep] = useState<"email" | "reset">("email"); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const send = async (event: FormEvent) => { event.preventDefault(); try { setLoading(true); setError(""); const data = await requestPasswordReset(email); setMessage(data.message); setStep("reset"); } catch (e: unknown) { setError(getErrorMessage(e, "குறியீட்டை அனுப்ப முடியவில்லை")); } finally { setLoading(false); } };
  const reset = async (event: FormEvent) => { event.preventDefault(); if (password !== confirm) { setError("கடவுச்சொற்கள் பொருந்தவில்லை"); return; } try { setLoading(true); setError(""); await resetPassword(email, otp, password); setMessage("கடவுச்சொல் மாற்றப்பட்டது. இப்போது உள்நுழையலாம்."); setTimeout(() => navigate("/login"), 1200); } catch (e: unknown) { setError(getErrorMessage(e, "கடவுச்சொல்லை மீட்டமைக்க முடியவில்லை")); } finally { setLoading(false); } };
  return <Box component="form" onSubmit={step === "email" ? send : reset}><Typography variant="h5" sx={{ fontWeight: 850 }}>கடவுச்சொல்லை மறந்துவிட்டீர்களா?</Typography><Typography color="text.secondary" sx={{ mt: 1, mb: 3 }}>{step === "email" ? "உங்கள் பதிவு செய்யப்பட்ட மின்னஞ்சலை உள்ளிடுங்கள்." : "மின்னஞ்சலுக்கு வந்த 6 இலக்கக் குறியீட்டையும் புதிய கடவுச்சொல்லையும் உள்ளிடுங்கள்."}</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{message && <Alert severity="info" sx={{ mb: 2 }}>{message}</Alert>}<Stack spacing={2}><TextField required type="email" label="மின்னஞ்சல்" value={email} disabled={step === "reset"} onChange={(e) => setEmail(e.target.value)} />{step === "reset" && <><TextField required label="6 இலக்கக் குறியீடு" value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g, "").slice(0, 6))} /><TextField required type="password" label="புதிய கடவுச்சொல்" value={password} helperText="8+ எழுத்துகள்; பெரிய, சிறிய எழுத்து, எண் மற்றும் சிறப்பு குறியீடு தேவை" onChange={(e) => setPassword(e.target.value)} /><TextField required type="password" label="புதிய கடவுச்சொல்லை மீண்டும் உள்ளிடுக" value={confirm} onChange={(e) => setConfirm(e.target.value)} /></>}<Button type="submit" variant="contained" size="large" disabled={loading || (step === "reset" && otp.length !== 6)}>{loading ? "செயல்படுத்தப்படுகிறது…" : step === "email" ? "குறியீட்டை அனுப்புக" : "கடவுச்சொல்லை மாற்றுக"}</Button>{step === "reset" && <Button onClick={() => void requestPasswordReset(email)}>குறியீட்டை மீண்டும் அனுப்புக</Button>}<Typography variant="body2" sx={{ textAlign: "center" }}><Link href="/login">உள்நுழைவுக்குத் திரும்புக</Link></Typography></Stack></Box>;
};
export default ForgotPassword;
