import { Router } from "express";
import { getAdminCounts, getAdminInventory, getAdminOrders, getAdminUsers, getDashboardOverview, getPerformanceAnalytics, updateOrderStatus, updateUserAccess } from "../controllers/adminController";
import { protect } from "../middleware/protect";
import { admin, adminOrApprovedStaff, requirePermission } from "../middleware/admin";
import { createBook, manageBookRemoval, updateBook } from "../controllers/bookController";
import upload from "../middleware/upload";
import { deleteContactMessage, getContactMessages, updateContactStatus, updateSiteContent } from "../controllers/contentController";
import { createCategory, deleteCategoryPermanently, getAdminCategories, updateCategory } from "../controllers/categoryController";

const router = Router();
router.use(protect);
router.use(adminOrApprovedStaff);
router.get("/overview", getDashboardOverview);
router.get("/performance", requirePermission("dashboard"), getPerformanceAnalytics);
router.get("/orders", requirePermission("orders"), getAdminOrders);
router.patch("/orders/:id/status", requirePermission("orders"), updateOrderStatus);
router.get("/inventory", requirePermission("products"), getAdminInventory);
router.get("/counts", getAdminCounts);
router.post("/products", requirePermission("products"), upload.array("images", 10), createBook);
router.put("/products/:id", requirePermission("products"), upload.array("images", 10), updateBook);
router.get("/users", admin, getAdminUsers);
router.patch("/users/:id/access", admin, updateUserAccess);
router.get("/contacts", admin, getContactMessages);
router.patch("/contacts/:id/status", admin, updateContactStatus);
router.delete("/contacts/:id", admin, deleteContactMessage);
router.put("/content", admin, upload.single("heroImage"), updateSiteContent);
router.delete("/products/:id", admin, manageBookRemoval);
router.get("/categories", admin, getAdminCategories);
router.post("/categories", admin, upload.single("image"), createCategory);
router.put("/categories/:id", admin, upload.single("image"), updateCategory);
router.delete("/categories/:id", admin, deleteCategoryPermanently);
export default router;
