import { useEffect, useState, type FormEvent } from "react";
import { Alert, Avatar, Box, Button, Divider, Grid, Paper, Rating, Stack, TextField, Typography } from "@mui/material";
import StarRoundedIcon from "@mui/icons-material/StarRounded";
import { useSelector } from "react-redux";
import { useNavigate } from "react-router-dom";
import type { RootState } from "../../store/store";
import { getBookReviews, saveBookReview, type BookReview } from "../../services/reviewService";
import { getErrorMessage } from "../../utils/getErrorMessage";

const BookReviews = ({ bookId }: { bookId: string }) => {
  const user = useSelector((state: RootState) => state.auth.user); const navigate = useNavigate();
  const [reviews, setReviews] = useState<BookReview[]>([]); const [average, setAverage] = useState(0); const [count, setCount] = useState(0); const [rating, setRating] = useState<number | null>(5); const [comment, setComment] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = async () => { const data = await getBookReviews(bookId); setReviews(data.reviews); setAverage(data.averageRating); setCount(data.reviewCount); setRating(5); setComment(""); };
  useEffect(() => { getBookReviews(bookId).then((data) => { setReviews(data.reviews); setAverage(data.averageRating); setCount(data.reviewCount); const own = data.reviews.find((review) => review.user._id === user?.id); if (own) { setRating(own.rating); setComment(own.comment); } }).catch(() => setError("மதிப்புரைகளை ஏற்ற முடியவில்லை")); }, [bookId, user?.id]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!user) { navigate("/login", { state: { from: { pathname: `/books/${bookId}`, search: "" } } }); return; } if (!rating) { setError("மதிப்பீட்டைத் தேர்ந்தெடுக்கவும்"); return; } try { setSaving(true); setError(""); await saveBookReview(bookId, rating, comment); await load(); setMessage("உங்கள் மதிப்புரை சேமிக்கப்பட்டது"); } catch (e: unknown) { setError(getErrorMessage(e, "மதிப்புரையைச் சேமிக்க முடியவில்லை")); } finally { setSaving(false); } };
  return <Box sx={{ mt: { xs: 7, md: 10 }, pt: { xs: 5, md: 7 }, borderTop: "1px solid", borderColor: "divider" }}><Grid container spacing={4}><Grid size={{ xs: 12, md: 4 }}><Typography variant="h3" sx={{ fontWeight: 900 }}>வாசகர் மதிப்புரைகள்</Typography><Stack direction="row" spacing={1.5} sx={{ alignItems: "center", mt: 2 }}><Typography variant="h2" sx={{ fontWeight: 900 }}>{average.toFixed(1)}</Typography><Box><Rating readOnly precision={.1} value={average} /><Typography variant="body2" color="text.secondary">{count} மதிப்புரைகள்</Typography></Box></Stack><Paper component="form" onSubmit={submit} elevation={0} sx={{ mt: 3, p: 3, border: "1px solid rgba(30,64,175,.12)", borderRadius: 3 }}><Typography sx={{ fontWeight: 850, mb: 1 }}>உங்கள் மதிப்பீடு</Typography><Rating value={rating} onChange={(_, value) => setRating(value)} size="large" /><TextField required fullWidth multiline minRows={4} label="உங்கள் மதிப்புரை" value={comment} onChange={(e) => setComment(e.target.value)} slotProps={{ htmlInput: { maxLength: 1000 } }} sx={{ mt: 2 }} />{error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}{message && <Alert severity="success" sx={{ mt: 2 }}>{message}</Alert>}<Button fullWidth type="submit" variant="contained" disabled={saving} sx={{ mt: 2 }}>{saving ? "சேமிக்கப்படுகிறது…" : user ? "மதிப்புரையைச் சேமிக்க" : "உள்நுழைந்து மதிப்பிடுக"}</Button></Paper></Grid><Grid size={{ xs: 12, md: 8 }}><Stack divider={<Divider flexItem />} spacing={0}>{reviews.length === 0 ? <Paper elevation={0} sx={{ p: 5, textAlign: "center", bgcolor: "rgba(30,64,175,.035)", borderRadius: 3 }}><StarRoundedIcon sx={{ fontSize: 52, color: "secondary.main" }} /><Typography variant="h6" sx={{ fontWeight: 800, mt: 1 }}>முதல் மதிப்புரையை நீங்கள் எழுதுங்கள்</Typography></Paper> : reviews.map((review) => <Box key={review._id} sx={{ py: 3 }}><Stack direction="row" spacing={2}><Avatar sx={{ bgcolor: "primary.main", fontWeight: 800 }}>{review.user.name[0]?.toUpperCase()}</Avatar><Box sx={{ flex: 1 }}><Stack direction={{ xs: "column", sm: "row" }} sx={{ justifyContent: "space-between" }}><Box><Typography sx={{ fontWeight: 850 }}>{review.user.name}</Typography><Rating readOnly size="small" value={review.rating} /></Box><Typography variant="caption" color="text.secondary">{new Date(review.updatedAt || review.createdAt).toLocaleDateString("ta-IN")}</Typography></Stack><Typography color="text.secondary" sx={{ mt: 1.5, lineHeight: 1.8, whiteSpace: "pre-wrap" }}>{review.comment}</Typography></Box></Stack></Box>)}</Stack></Grid></Grid></Box>;
};
export default BookReviews;
