import { useEffect, useState } from "react";
import { Alert, Box, Button, Chip, CircularProgress, MenuItem, Paper, Select, Stack, Typography } from "@mui/material";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutlined";
import ReplyOutlinedIcon from "@mui/icons-material/ReplyOutlined";
import { deleteContactMessage, getAdminContacts, updateContactStatus, type ContactMessage } from "../../services/adminService";
import { getErrorMessage } from "../../utils/getErrorMessage";

const Contacts = () => {
  const [messages, setMessages] = useState<ContactMessage[]>([]); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(""); const [error, setError] = useState("");
  useEffect(() => { getAdminContacts().then(setMessages).catch((e: unknown) => setError(getErrorMessage(e, "Unable to load messages"))).finally(() => setLoading(false)); }, []);
  const setStatus = async (id: string, status: ContactMessage["status"]) => { try { setWorking(id); const updated = await updateContactStatus(id, status); setMessages((items) => items.map((item) => item._id === id ? updated : item)); } catch (e: unknown) { setError(getErrorMessage(e, "Unable to change status")); } finally { setWorking(""); } };
  const remove = async (id: string) => { if (!window.confirm("Permanently delete this message?")) return; try { setWorking(id); await deleteContactMessage(id); setMessages((items) => items.filter((item) => item._id !== id)); } catch (e: unknown) { setError(getErrorMessage(e, "Unable to delete message")); } finally { setWorking(""); } };
  if (loading) return <Box sx={{ minHeight: 360, display: "grid", placeItems: "center" }}><CircularProgress /></Box>;
  return <Stack spacing={3}><Box><Typography variant="h4" sx={{ fontWeight: 900 }}>Contact messages</Typography><Typography color="text.secondary">Total {messages.length} · New {messages.filter((item) => item.status === "new").length}</Typography></Box>{error && <Alert severity="error" onClose={() => setError("")}>{error}</Alert>}{messages.length === 0 ? <Paper variant="outlined" sx={{ p: 5, textAlign: "center", borderRadius: 3 }}><Typography color="text.secondary">No contact messages.</Typography></Paper> : messages.map((item) => <Paper key={item._id} elevation={0} sx={{ p: { xs: 2, md: 3 }, border: "1px solid #E3E8E5", borderRadius: 3, borderLeft: item.status === "new" ? "4px solid #C99935" : undefined }}><Stack direction={{ xs: "column", md: "row" }} spacing={2.5} sx={{ justifyContent: "space-between" }}><Box sx={{ minWidth: 0, flex: 1 }}><Stack direction="row" spacing={1} sx={{ alignItems: "center", flexWrap: "wrap" }}><Typography variant="h6" sx={{ fontWeight: 850 }}>{item.subject}</Typography>{item.status === "new" && <Chip label="New" color="warning" size="small" />}</Stack><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>{item.name} · {item.email} · {new Date(item.createdAt).toLocaleString("en-IN")}</Typography><Typography sx={{ mt: 2, whiteSpace: "pre-wrap", lineHeight: 1.75 }}>{item.message}</Typography></Box><Stack spacing={1.2} sx={{ width: { xs: "100%", md: 180 }, flexShrink: 0 }}><Select size="small" value={item.status} disabled={working === item._id} onChange={(e) => void setStatus(item._id, e.target.value as ContactMessage["status"])}><MenuItem value="new">New</MenuItem><MenuItem value="read">Read</MenuItem><MenuItem value="resolved">Resolved</MenuItem></Select><Button component="a" href={`mailto:${item.email}?subject=${encodeURIComponent(`Re: ${item.subject}`)}`} variant="contained" startIcon={<ReplyOutlinedIcon />}>Reply</Button><Button color="error" startIcon={<DeleteOutlineIcon />} disabled={working === item._id} onClick={() => void remove(item._id)}>Delete</Button></Stack></Stack></Paper>)}</Stack>;
};
export default Contacts;
