import { useEffect, useState } from "react";
import { Alert, Box, Button, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Grid, IconButton, MenuItem, Paper, Stack, TextField, Tooltip, Typography } from "@mui/material";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import DeleteOutlinedIcon from "@mui/icons-material/DeleteOutlined";
import { createAdminCoupon, deleteAdminCoupon, getAdminCoupons, updateAdminCoupon, type AdminCoupon, type CouponInput } from "../../services/adminService";
import { getErrorMessage } from "../../utils/getErrorMessage";

const blank: CouponInput = { code: "", discountType: "percentage", discountValue: "", minOrderAmount: "0", maxDiscount: "", usageLimit: "", perUserLimit: "1", expiresAt: "", isActive: true };
const Coupons = () => {
  const [coupons, setCoupons] = useState<AdminCoupon[]>([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<AdminCoupon | null>(null); const [deleting, setDeleting] = useState<AdminCoupon | null>(null); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = async () => setCoupons(await getAdminCoupons());
  useEffect(() => { getAdminCoupons().then(setCoupons).catch((e: unknown) => setError(getErrorMessage(e, "Unable to load coupons"))); }, []);
  const startNew = () => { setEditing(null); setForm(blank); setOpen(true); };
  const startEdit = (coupon: AdminCoupon) => { setEditing(coupon); setForm({ code: coupon.code, discountType: coupon.discountType, discountValue: String(coupon.discountValue), minOrderAmount: String(coupon.minimumOrderAmount), maxDiscount: coupon.maximumDiscountAmount === undefined ? "" : String(coupon.maximumDiscountAmount), usageLimit: coupon.usageLimit === undefined ? "" : String(coupon.usageLimit), perUserLimit: String(coupon.perUserLimit), expiresAt: coupon.expiresAt.slice(0, 10), isActive: coupon.isActive }); setOpen(true); };
  const save = async () => { try { setSaving(true); setError(""); if (editing) await updateAdminCoupon(editing._id, form); else await createAdminCoupon(form); await load(); setOpen(false); } catch (e: unknown) { setError(getErrorMessage(e, "Unable to save coupon")); } finally { setSaving(false); } };
  const remove = async () => { if (!deleting) return; try { setSaving(true); await deleteAdminCoupon(deleting._id); await load(); setDeleting(null); } catch (e: unknown) { setError(getErrorMessage(e, "Unable to delete coupon")); } finally { setSaving(false); } };
  const field = (key: keyof CouponInput, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  return <Box>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Stack direction={{ xs: "column", sm: "row" }} sx={{ justifyContent: "space-between", alignItems: { sm: "center" }, gap: 2, mb: 3 }}><Box><Typography variant="h5" sx={{ fontWeight: 850 }}>Coupons</Typography><Typography color="text.secondary">Create and manage discount coupons.</Typography></Box><Button variant="contained" startIcon={<AddOutlinedIcon />} onClick={startNew}>Create coupon</Button></Stack><Grid container spacing={2}>{coupons.map((coupon) => { const expired = new Date(coupon.expiresAt) < new Date(); return <Grid key={coupon._id} size={{ xs: 12, md: 6, xl: 4 }}><Paper elevation={0} sx={{ p: 3, border: "1px solid #E3E8E5", borderRadius: 3 }}><Stack direction="row" sx={{ justifyContent: "space-between" }}><Box><Typography variant="h5" sx={{ fontWeight: 900, letterSpacing: ".06em" }}>{coupon.code}</Typography><Typography color="primary.main" sx={{ fontWeight: 800 }}>{coupon.discountType === "percentage" ? `${coupon.discountValue}% off` : `₹${coupon.discountValue} off`}</Typography></Box><Chip size="small" color={!coupon.isActive || expired ? "default" : "success"} label={expired ? "Expired" : coupon.isActive ? "Active" : "Disabled"} /></Stack><Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>Minimum order: ₹{coupon.minimumOrderAmount}<br />Usage: {coupon.usedCount}{coupon.usageLimit ? ` / ${coupon.usageLimit}` : ""}<br />Expired: {new Date(coupon.expiresAt).toLocaleDateString("en-IN")}</Typography><Stack direction="row" sx={{ mt: 2 }}><Tooltip title="Edit"><IconButton onClick={() => startEdit(coupon)}><EditOutlinedIcon /></IconButton></Tooltip><Tooltip title="Delete"><IconButton color="error" onClick={() => setDeleting(coupon)}><DeleteOutlinedIcon /></IconButton></Tooltip></Stack></Paper></Grid>; })}</Grid>
    <Dialog open={open} onClose={() => !saving && setOpen(false)} maxWidth="sm" fullWidth><DialogTitle sx={{ fontWeight: 850 }}>{editing ? "Edit coupon" : "New coupon"}</DialogTitle><DialogContent><Grid container spacing={2} sx={{ mt: .5 }}><F label="Coupon code" value={form.code} set={(v) => field("code", v.toUpperCase())} disabled={Boolean(editing)} /><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth select label="off Category" value={form.discountType} onChange={(e) => field("discountType", e.target.value)}><MenuItem value="percentage">Percentage</MenuItem><MenuItem value="fixed">Fixed amount</MenuItem></TextField></Grid><F label="Discount value" type="number" value={form.discountValue} set={(v) => field("discountValue", v)} /><F label="Minimum order" type="number" value={form.minOrderAmount} set={(v) => field("minOrderAmount", v)} /><F label="Maximum discount" type="number" value={form.maxDiscount} set={(v) => field("maxDiscount", v)} /><F label="Total usage limit" type="number" value={form.usageLimit} set={(v) => field("usageLimit", v)} /><F label="Per-user limit" type="number" value={form.perUserLimit} set={(v) => field("perUserLimit", v)} /><F label="Expiry date" type="date" value={form.expiresAt} set={(v) => field("expiresAt", v)} /><Grid size={{ xs: 12 }}><FormControlLabel control={<Checkbox checked={form.isActive} onChange={(e) => field("isActive", e.target.checked)} />} label="Active" /></Grid></Grid></DialogContent><DialogActions sx={{ p: 3 }}><Button onClick={() => setOpen(false)}>Cancel</Button><Button variant="contained" disabled={saving || !form.code || !form.discountValue || !form.expiresAt} onClick={() => void save()}>{saving ? "Saving…" : "Save"}</Button></DialogActions></Dialog>
    <Dialog open={Boolean(deleting)} onClose={() => !saving && setDeleting(null)}><DialogTitle sx={{ fontWeight: 850 }}>Delete coupon?</DialogTitle><DialogContent><Typography>“{deleting?.code}” coupon and its usage records will be permanently deleted.</Typography></DialogContent><DialogActions><Button onClick={() => setDeleting(null)}>Cancel</Button><Button variant="contained" color="error" disabled={saving} onClick={() => void remove()}>Delete permanently</Button></DialogActions></Dialog>
  </Box>;
};
const F = ({ label, value, set, type = "text", disabled = false }: { label: string; value: string; set: (value: string) => void; type?: string; disabled?: boolean }) => <Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label={label} value={value} type={type} disabled={disabled} onChange={(e) => set(e.target.value)} slotProps={type === "date" ? { inputLabel: { shrink: true } } : undefined} /></Grid>;
export default Coupons;
