import { useEffect, useState } from "react";
import { Alert, Box, Button, Checkbox, Chip, CircularProgress, FormControlLabel, Grid, IconButton, MenuItem, Paper, Select, Stack, TextField, Typography } from "@mui/material";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import DeleteOutlinedIcon from "@mui/icons-material/DeleteOutlined";
import { getAdminContacts, getSiteContent, updateContactStatus, updateSiteContent, type ContactMessage, type SiteContent as SiteContentData } from "../../services/adminService";
import { getErrorMessage } from "../../utils/getErrorMessage";

const SiteContent = () => {
  const [content, setContent] = useState<SiteContentData | null>(null);
  const [messages, setMessages] = useState<ContactMessage[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [heroImage, setHeroImage] = useState<File | undefined>();
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");

  useEffect(() => { Promise.all([getSiteContent(), getAdminContacts()]).then(([site, contacts]) => { setContent(site); setMessages(contacts); }).catch((e: unknown) => setError(getErrorMessage(e, "Unable to load data"))).finally(() => setLoading(false)); }, []);
  const change = (section: keyof SiteContentData, field: string, value: unknown) => setContent((current) => current ? { ...current, [section]: { ...current[section], [field]: value } } : current);
  const save = async () => { if (!content) return; try { setSaving(true); setError(""); setContent(await updateSiteContent(content, heroImage)); setHeroImage(undefined); setNotice("Website content updated"); } catch (e: unknown) { setError(getErrorMessage(e, "Unable to update")); } finally { setSaving(false); } };
  const setStatus = async (id: string, status: ContactMessage["status"]) => { try { const updated = await updateContactStatus(id, status); setMessages((current) => current.map((item) => item._id === id ? updated : item)); } catch (e: unknown) { setError(getErrorMessage(e, "Message Unable to change status")); } };
  if (loading) return <Box sx={{ minHeight: 400, display: "grid", placeItems: "center" }}><CircularProgress /></Box>;
  if (!content) return <Alert severity="error">Content is unavailable</Alert>;
  const aboutFields: [keyof SiteContentData["about"], string][] = [["eyebrow", "Eyebrow"], ["heading", "Main heading"], ["title", "Company name"], ["description", "About us description"]];
  const heroFields: [keyof SiteContentData["hero"], string][] = [["badge", "Hero badge"], ["heading", "Hero Title"], ["description", "Hero Description"], ["primaryButton", "Primary button"], ["secondaryButton", "Secondary button"]];
  const footerFields: [keyof SiteContentData["footer"], string][] = [["description", "Footer Description"], ["email", "Email"], ["phone", "Phone"], ["address", "Address"], ["workingHours", "Working hours"], ["copyright", "Copyright text"]];
  return <Stack spacing={3}>
    <Box><Typography variant="h4" sx={{ fontWeight: 900 }}>Website content management</Typography><Typography color="text.secondary">Manage About Us, footer, and customer contact messages in one place.</Typography></Box>
    {error && <Alert severity="error" onClose={() => setError("")}>{error}</Alert>}{notice && <Alert severity="success" onClose={() => setNotice("")}>{notice}</Alert>}
    <Paper elevation={0} sx={{ p: { xs: 2.5, md: 4 }, border: "1px solid #E3E8E5", borderRadius: 3 }}><Typography variant="h5" sx={{ fontWeight: 850 }}>Navbar Running Line</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Add, edit, or delete announcements and configure the ticker appearance and speed.</Typography><FormControlLabel control={<Checkbox checked={content.announcement.enabled} onChange={(e) => change("announcement", "enabled", e.target.checked)} />} label="Show announcement ticker" /><Stack spacing={1.5} sx={{ mt: 2 }}>{content.announcement.messages.map((message, index) => <Stack key={index} direction="row" spacing={1}><TextField fullWidth label={`Message ${index + 1}`} value={message} onChange={(e) => { const next = [...content.announcement.messages]; next[index] = e.target.value; change("announcement", "messages", next); }} /><IconButton color="error" onClick={() => change("announcement", "messages", content.announcement.messages.filter((_, itemIndex) => itemIndex !== index))}><DeleteOutlinedIcon /></IconButton></Stack>)}</Stack><Button startIcon={<AddOutlinedIcon />} onClick={() => change("announcement", "messages", [...content.announcement.messages, "New announcement"])} sx={{ mt: 2 }}>Add message</Button><Grid container spacing={2} sx={{ mt: 1 }}><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth type="number" label="Running speed (seconds)" value={content.announcement.speed} slotProps={{ htmlInput: { min: 5, max: 120 } }} onChange={(e) => change("announcement", "speed", Number(e.target.value))} helperText="Lower number = faster speed" /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth type="number" label="Font size (px)" value={content.announcement.fontSize} slotProps={{ htmlInput: { min: 10, max: 24 } }} onChange={(e) => change("announcement", "fontSize", Number(e.target.value))} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth type="color" label="Text color" value={content.announcement.textColor} onChange={(e) => change("announcement", "textColor", e.target.value)} slotProps={{ inputLabel: { shrink: true } }} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth type="color" label="Background color" value={content.announcement.backgroundColor} onChange={(e) => change("announcement", "backgroundColor", e.target.value)} slotProps={{ inputLabel: { shrink: true } }} /></Grid></Grid><Box sx={{ mt: 3, overflow: "hidden", bgcolor: content.announcement.backgroundColor, color: content.announcement.textColor, p: 1.2, borderRadius: 1 }}><Typography noWrap sx={{ fontSize: `${content.announcement.fontSize}px` }}>{content.announcement.messages.join("   ◆   ") || "Preview"}</Typography></Box><Button variant="contained" disabled={saving} onClick={() => void save()} sx={{ mt: 3 }}>{saving ? "Saving…" : "Running line Save"}</Button></Paper>
    <Paper elevation={0} sx={{ p: { xs: 2.5, md: 4 }, border: "1px solid #E3E8E5", borderRadius: 3 }}><Typography variant="h5" sx={{ fontWeight: 850, mb: 3 }}>Home page hero</Typography><Grid container spacing={2}>{heroFields.map(([field, label]) => <Grid key={field} size={{ xs: 12, md: field === "heading" || field === "description" ? 12 : 6 }}><TextField fullWidth multiline={field === "heading" || field === "description"} label={label} value={content.hero[field]} onChange={(e) => change("hero", field, e.target.value)} /></Grid>)}<Grid size={{ xs: 12 }}><Button component="label" variant="outlined">Choose hero background image<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setHeroImage(e.target.files?.[0])} /></Button><Typography variant="caption" sx={{ ml: 2 }}>{heroImage?.name || (content.hero.imageUrl ? "Current images will be kept" : "No image selected")}</Typography>{content.hero.imageUrl && <Box component="img" src={content.hero.imageUrl} alt="Hero preview" sx={{ display: "block", mt: 2, width: "100%", maxHeight: 260, objectFit: "cover", borderRadius: 2 }} />}</Grid></Grid></Paper>
    <Paper elevation={0} sx={{ p: { xs: 2.5, md: 4 }, border: "1px solid #E3E8E5", borderRadius: 3 }}><Typography variant="h5" sx={{ fontWeight: 850, mb: 3 }}>About us</Typography><Grid container spacing={2}>{aboutFields.map(([field, label]) => <Grid key={field} size={{ xs: 12, md: field === "description" || field === "heading" ? 12 : 6 }}><TextField fullWidth multiline={field === "description" || field === "heading"} minRows={field === "description" ? 4 : undefined} label={label} value={content.about[field]} onChange={(e) => change("about", field, e.target.value)} /></Grid>)}</Grid></Paper>
    <Paper elevation={0} sx={{ p: { xs: 2.5, md: 4 }, border: "1px solid #E3E8E5", borderRadius: 3 }}><Typography variant="h5" sx={{ fontWeight: 850, mb: 3 }}>Footer information</Typography><Grid container spacing={2}>{footerFields.map(([field, label]) => <Grid key={field} size={{ xs: 12, md: field === "description" || field === "copyright" ? 12 : 6 }}><TextField fullWidth multiline={field === "description"} minRows={field === "description" ? 3 : undefined} label={label} value={content.footer[field]} onChange={(e) => change("footer", field, e.target.value)} /></Grid>)}</Grid><Button variant="contained" size="large" disabled={saving} onClick={() => void save()} sx={{ mt: 3 }}>{saving ? "Saving…" : "Save changes"}</Button></Paper>
    <Paper elevation={0} sx={{ p: { xs: 2.5, md: 4 }, border: "1px solid #E3E8E5", borderRadius: 3 }}><Stack direction={{ xs: "column", sm: "row" }} sx={{ justifyContent: "space-between", mb: 3 }}><Box><Typography variant="h5" sx={{ fontWeight: 850 }}>Contact Us Messages</Typography><Typography color="text.secondary">Total {messages.length} Messages · {messages.filter((item) => item.status === "new").length} New</Typography></Box></Stack><Stack spacing={2}>{messages.length === 0 ? <Typography color="text.secondary">No messages.</Typography> : messages.map((item) => <Paper key={item._id} variant="outlined" sx={{ p: 2.5, borderRadius: 2.5 }}><Stack direction={{ xs: "column", md: "row" }} spacing={2} sx={{ justifyContent: "space-between" }}><Box sx={{ flex: 1 }}><Stack direction="row" spacing={1} sx={{ alignItems: "center", flexWrap: "wrap" }}><Typography sx={{ fontWeight: 850 }}>{item.subject}</Typography>{item.status === "new" && <Chip size="small" color="warning" label="New" />}</Stack><Typography variant="body2" color="text.secondary">{item.name} · {item.email} · {new Date(item.createdAt).toLocaleDateString("en-IN")}</Typography><Typography sx={{ mt: 1.5, whiteSpace: "pre-wrap" }}>{item.message}</Typography></Box><Select size="small" value={item.status} onChange={(e) => void setStatus(item._id, e.target.value as ContactMessage["status"])} sx={{ minWidth: 145, alignSelf: "flex-start" }}><MenuItem value="new">New</MenuItem><MenuItem value="read">Read</MenuItem><MenuItem value="resolved">Resolved</MenuItem></Select></Stack></Paper>)}</Stack></Paper>
  </Stack>;
};
export default SiteContent;
